services:
  db:
    image: postgres:15
    container_name: EksamenSys_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: SuperSecurePassword123
      POSTGRES_DB: EksamenSys_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dbInit:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    name: EksamenSys_db_data

